services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    command: gunicorn main_course.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_NAME=#
      - DATABASE_USER=#
      - DATABASE_PASSWORD=#
      - DATABASE_HOST=#

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=#
      - POSTGRES_USER=#
      - POSTGRES_PASSWORD=#
    command: postgres -c listen_addresses='*'
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
  media_volume:
