# Generated by Django 5.1.7 on 2025-05-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_pay',
            name='expire_date',
            field=models.DateTimeField(),
        ),
    ]
